### ISSUE TITLE
in nuxes5 ,it crashes

### ISSUE THREAD

**Issue by swepthong** [soywiz/android-ktor-example#1]
problem:
Process: com.soywiz.myapplication, PID: 528
    java.lang.NoClassDefFoundError: io.ktor.application.ApplicationEvents$subscribe$1
        at io.ktor.application.ApplicationEvents.subscribe(ApplicationEvents.kt:18)
        at io.ktor.server.engine.BaseApplicationEngine.<init>(BaseApplicationEngine.kt:29)
        at io.ktor.server.engine.BaseApplicationEngine.<init>(BaseApplicationEngine.kt:15)
        at io.ktor.server.netty.NettyApplicationEngine.<init>(NettyApplicationEngine.kt:17)
        at io.ktor.server.netty.Netty.create(Embedded.kt:10)
        at io.ktor.server.netty.Netty.create(Embedded.kt:8)
        at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:50)
        at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:40)
        at io.ktor.server.engine.EmbeddedServerKt.embeddedServer$default(EmbeddedServer.kt:27)
        at com.soywiz.myapplication.KtorFetchService.onCreate(KtorFetchService.kt:23)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
        at android.app.ActivityThread.-wrap4(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by swepthong** [comment]
@soywiz   could you help?
